[application]
name = "yurtur-top"
default_platform = "web"
out_dir = "docs"
base_path = "yurtur.top"
asset_dir = "public"

[web.app]
title = "Yurtur | Your turn to innovations"
index_on_404 = true

[web.watcher]
watch_path = ["src", "public", "tailwind.config.js"]
index_on_404 = true

[web.resource]
style = ["tailwind.css"]

script = []

[web.resource.dev]
style = []
script = []

[application.plugins]
available = true
required = []
